import { sql, type Kysely } from 'kysely';

export async function up(database: Kysely<unknown>): Promise<void> {
  await sql.raw(AUTHORIZATION_SQL).execute(database);
}

const AUTHORIZATION_SQL = `
-- Phase 4 authorization relationships: explicit grants cover only duties
-- without a canonical school relationship. Student/teacher authority comes
-- from organization_membership / section_membership, never authorization_grant.
DO $$
DECLARE
  legacy_count bigint;
BEGIN
  SELECT count(*) INTO legacy_count
  FROM authorization_grant
  WHERE role IN ('student', 'teacher');
  IF legacy_count > 0 THEN
    RAISE EXCEPTION
      '004 authorization migration: % legacy student/teacher authorization_grant row(s) exist; resolve manually, refusing to reinterpret them',
      legacy_count;
  END IF;
END $$;

-- Narrow the role vocabulary to explicit duties only. The foundation CHECK
-- already permits this subset, so an additive CHECK is sufficient and avoids
-- depending on the autogenerated foundation constraint name.
ALTER TABLE authorization_grant
  ADD CONSTRAINT authorization_grant_phase4_role_check
  CHECK (role IN ('destination_staff', 'counselor', 'office_staff', 'school_admin', 'system_admin'));

-- Exact role/scope combinations. No valid Phase 4 grant uses section scope;
-- the legacy section_id/scope infrastructure stays physically present for
-- forward compatibility but cannot satisfy this constraint.
ALTER TABLE authorization_grant
  ADD CONSTRAINT authorization_grant_phase4_role_scope_check
  CHECK (
    (role = 'system_admin' AND scope_kind = 'tenant'
      AND organization_id IS NULL AND section_id IS NULL AND destination_id IS NULL)
    OR (role = 'school_admin' AND scope_kind = 'organization'
      AND organization_id IS NOT NULL AND section_id IS NULL AND destination_id IS NULL)
    OR (role = 'counselor' AND scope_kind = 'organization'
      AND organization_id IS NOT NULL AND section_id IS NULL AND destination_id IS NULL)
    OR (role = 'office_staff' AND scope_kind = 'organization'
      AND organization_id IS NOT NULL AND section_id IS NULL AND destination_id IS NULL)
    OR (role = 'destination_staff' AND scope_kind = 'destination'
      AND organization_id IS NULL AND section_id IS NULL AND destination_id IS NOT NULL)
  );

-- Person-first active-membership lookup. The existing semantic uniqueness is
-- organization-first (tenant, organization, person, affiliation); Phase 4
-- loads by person across schools (accessible organizations, per-school
-- membership validity), so this index serves the actual query shape.
CREATE INDEX organization_membership_phase4_person_active_idx
  ON organization_membership (tenant_id, person_id, organization_id, affiliation)
  WHERE status = 'active';

-- Active-account grant lookup for per-decision evaluation:
-- (tenant, account, role, scope) with row-validity filtered in memory
-- against Temporal.Instant half-open semantics.
CREATE INDEX authorization_grant_phase4_account_active_idx
  ON authorization_grant (tenant_id, account_id, role, scope_kind)
  WHERE status = 'active';
`;
