import { sql, type Kysely } from 'kysely';

export async function up(database: Kysely<unknown>): Promise<void> {
  await sql.raw(PASS_COMMAND_CORE_SQL).execute(database);
}

const PASS_COMMAND_CORE_SQL = `
-- Phase 5 pass command core: harden same-school integrity (forward-only).
-- Migrations 001-004 are never modified; everything here is additive.

-- 0. Preflight: refuse to silently rewrite historical cross-school passes.
DO $$
DECLARE
  bad_destination bigint;
  bad_section bigint;
  bad_origin_location bigint;
  bad_return_location bigint;
BEGIN
  SELECT count(*) INTO bad_destination
  FROM pass p
  JOIN destination d ON d.tenant_id = p.tenant_id AND d.id = p.destination_id
  WHERE d.organization_id <> p.organization_id;
  IF bad_destination > 0 THEN
    RAISE EXCEPTION
      '005 pass command core: % existing pass row(s) reference a destination in another school; resolve manually',
      bad_destination;
  END IF;

  SELECT count(*) INTO bad_section
  FROM pass p
  JOIN section s ON s.tenant_id = p.tenant_id AND s.id = p.origin_section_id
  WHERE p.origin_section_id IS NOT NULL AND s.organization_id <> p.organization_id;
  IF bad_section > 0 THEN
    RAISE EXCEPTION
      '005 pass command core: % existing pass row(s) reference an origin section in another school; resolve manually',
      bad_section;
  END IF;

  SELECT count(*) INTO bad_origin_location
  FROM pass p
  JOIN location l ON l.tenant_id = p.tenant_id AND l.id = p.origin_location_id
  WHERE p.origin_location_id IS NOT NULL AND l.organization_id <> p.organization_id;
  IF bad_origin_location > 0 THEN
    RAISE EXCEPTION
      '005 pass command core: % existing pass row(s) reference an origin location in another school; resolve manually',
      bad_origin_location;
  END IF;

  SELECT count(*) INTO bad_return_location
  FROM pass p
  JOIN location l ON l.tenant_id = p.tenant_id AND l.id = p.return_location_id
  WHERE p.return_location_id IS NOT NULL AND l.organization_id <> p.organization_id;
  IF bad_return_location > 0 THEN
    RAISE EXCEPTION
      '005 pass command core: % existing pass row(s) reference a return location in another school; resolve manually',
      bad_return_location;
  END IF;
END $$;

-- 1. Composite uniqueness so same-school composite foreign keys are supported.
-- destination is explicitly required; location/section/schedule_block get the
-- same treatment so their pass FKs can bind (tenant, school, resource).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'destination_phase5_tenant_school_key'
  ) THEN
    ALTER TABLE destination
      ADD CONSTRAINT destination_phase5_tenant_school_key
      UNIQUE (tenant_id, organization_id, id);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'location_phase5_tenant_school_key'
  ) THEN
    ALTER TABLE location
      ADD CONSTRAINT location_phase5_tenant_school_key
      UNIQUE (tenant_id, organization_id, id);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'section_phase5_tenant_school_key'
  ) THEN
    ALTER TABLE section
      ADD CONSTRAINT section_phase5_tenant_school_key
      UNIQUE (tenant_id, organization_id, id);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'schedule_block_phase5_tenant_school_key'
  ) THEN
    ALTER TABLE schedule_block
      ADD CONSTRAINT schedule_block_phase5_tenant_school_key
      UNIQUE (tenant_id, organization_id, id);
  END IF;
END $$;

-- 2. Historical origin schedule-block snapshot (new column backfills as NULL).
ALTER TABLE pass
  ADD COLUMN IF NOT EXISTS origin_schedule_block_id uuid;

-- 3. Drop the legacy tenant-only pass FKs so they can be replaced by
-- same-school composite FKs. Constraint names are autogenerated, so drop by
-- lookup instead of by name.
DO $$
DECLARE
  fk record;
BEGIN
  FOR fk IN
    SELECT conname, conrelid::regclass AS table_name
    FROM pg_constraint
    WHERE contype = 'f'
      AND conrelid = 'pass'::regclass
      AND array_length(conkey, 1) = 2
  LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', fk.table_name, fk.conname);
  END LOOP;
END $$;

-- 4. Same-school composite foreign keys: every non-null child reference must
-- belong to the same school as pass.organization_id. student_id is
-- intentionally untouched (Person is tenant-wide; membership is an
-- application invariant). requested_by_person_id and
-- scheduled_authorization_id stay tenant-bound.
ALTER TABLE pass
  ADD CONSTRAINT pass_phase5_destination_same_school
  FOREIGN KEY (tenant_id, organization_id, destination_id)
  REFERENCES destination (tenant_id, organization_id, id),
  ADD CONSTRAINT pass_phase5_origin_location_same_school
  FOREIGN KEY (tenant_id, organization_id, origin_location_id)
  REFERENCES location (tenant_id, organization_id, id),
  ADD CONSTRAINT pass_phase5_return_location_same_school
  FOREIGN KEY (tenant_id, organization_id, return_location_id)
  REFERENCES location (tenant_id, organization_id, id),
  ADD CONSTRAINT pass_phase5_origin_section_same_school
  FOREIGN KEY (tenant_id, organization_id, origin_section_id)
  REFERENCES section (tenant_id, organization_id, id),
  ADD CONSTRAINT pass_phase5_origin_block_same_school
  FOREIGN KEY (tenant_id, organization_id, origin_schedule_block_id)
  REFERENCES schedule_block (tenant_id, organization_id, id);

-- Keep the tenant-bound references that must not become school-bound.
ALTER TABLE pass
  ADD CONSTRAINT pass_phase5_student_tenant_fk
  FOREIGN KEY (tenant_id, student_id) REFERENCES person (tenant_id, id),
  ADD CONSTRAINT pass_phase5_requested_by_tenant_fk
  FOREIGN KEY (tenant_id, requested_by_person_id) REFERENCES person (tenant_id, id),
  ADD CONSTRAINT pass_phase5_scheduled_auth_tenant_fk
  FOREIGN KEY (tenant_id, scheduled_authorization_id)
  REFERENCES scheduled_authorization (tenant_id, id),
  ADD CONSTRAINT pass_phase5_organization_tenant_fk
  FOREIGN KEY (tenant_id, organization_id) REFERENCES organization (tenant_id, id);
`;
