import { sql, type Kysely } from 'kysely';

export async function up(database: Kysely<unknown>): Promise<void> {
  await sql.raw(DESTINATION_FLOW_AND_MOVEMENT_SQL).execute(database);
}

const DESTINATION_FLOW_AND_MOVEMENT_SQL = `
-- Phase 7 destination flow, capacity leases, queues, and explicit movement
-- (forward-only). Migrations 001-006 are never modified; everything here is
-- additive, except the dormant flow-table redefinition below, which is
-- provably empty via the preflight.

-- 0. Preflight: destination_reservation and queue_entry have never been
-- operational application data. Refuse to invent policy clearance, flow
-- deadlines, claim times, release reasons, or organizations for legacy rows.
DO $$
DECLARE
  legacy_reservations bigint;
  legacy_queue_entries bigint;
BEGIN
  SELECT count(*) INTO legacy_reservations FROM destination_reservation;
  IF legacy_reservations > 0 THEN
    RAISE EXCEPTION
      '007 destination flow: % existing destination_reservation row(s) predate operational flow semantics; OpenHall never recorded policy clearance, flow deadlines, claim times, release reasons, or organizations for them, resolve manually',
      legacy_reservations;
  END IF;

  SELECT count(*) INTO legacy_queue_entries FROM queue_entry;
  IF legacy_queue_entries > 0 THEN
    RAISE EXCEPTION
      '007 destination flow: % existing queue_entry row(s) predate operational queue semantics; OpenHall never recorded policy clearance, flow deadlines, release reasons, or organizations for them, resolve manually',
      legacy_queue_entries;
  END IF;
END $$;

-- 1. Destination flow timeouts. Capacity, queue_enabled, check_in_mode,
-- durations, and status are untouched.
ALTER TABLE destination
  ADD COLUMN ready_claim_timeout_seconds integer NOT NULL DEFAULT 60,
  ADD COLUMN queue_timeout_seconds integer NOT NULL DEFAULT 600;

ALTER TABLE destination
  ADD CONSTRAINT destination_phase7_ready_claim_bounds
  CHECK (ready_claim_timeout_seconds BETWEEN 5 AND 600),
  ADD CONSTRAINT destination_phase7_queue_timeout_bounds
  CHECK (queue_timeout_seconds BETWEEN 60 AND 14400);

-- 2. Operational binding key: an evaluation is addressable within its pass so
-- reservation/queue rows can reference the exact allow evaluation that
-- cleared their operational step through a composite foreign key.
ALTER TABLE policy_evaluation
  ADD CONSTRAINT policy_evaluation_phase7_pass_binding
  UNIQUE (tenant_id, pass_id, id);

-- 3. Same-school pass key so operational rows can bind
-- (tenant, school, pass) with composite foreign keys.
ALTER TABLE pass
  ADD CONSTRAINT pass_phase7_tenant_school_key
  UNIQUE (tenant_id, organization_id, id);

-- 4. Harden destination_reservation into the capacity source of truth.
-- The foundation table was never operationally used, so expires_at becomes
-- the explicitly named ready_expires_at claim deadline.
ALTER TABLE destination_reservation
  RENAME COLUMN expires_at TO ready_expires_at;

-- Drop the foundation nullable-expiry CHECK (autogenerated name: lookup, as
-- in 005/006); coherence below replaces it. The foundation released_at lower
-- bound is an exact duplicate of the Phase 7 release check, so it goes too.
DO $$
DECLARE
  stale record;
BEGIN
  FOR stale IN
    SELECT conname, conrelid::regclass AS table_name
    FROM pg_constraint
    WHERE contype = 'c'
      AND conrelid = 'destination_reservation'::regclass
      AND (
        pg_get_constraintdef(oid) LIKE '%ready_expires_at%reserved_at%'
        OR pg_get_constraintdef(oid) LIKE '%released_at%reserved_at%'
      )
  LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', stale.table_name, stale.conname);
  END LOOP;
END $$;

-- Drop the legacy tenant-only flow FKs (autogenerated names) so they can be
-- replaced by same-school composite FKs plus the policy binding.
DO $$
DECLARE
  fk record;
BEGIN
  FOR fk IN
    SELECT conname, conrelid::regclass AS table_name
    FROM pg_constraint
    WHERE contype = 'f'
      AND conrelid = 'destination_reservation'::regclass
      AND array_length(conkey, 1) = 2
  LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', fk.table_name, fk.conname);
  END LOOP;
END $$;

-- The preflight guarantees an empty table, so tightening is honest.
ALTER TABLE destination_reservation
  ADD COLUMN organization_id uuid NOT NULL,
  ADD COLUMN policy_evaluation_id uuid NOT NULL,
  ADD COLUMN claimed_at timestamptz,
  ADD COLUMN flow_expires_at timestamptz NOT NULL,
  ADD COLUMN release_reason text;

ALTER TABLE destination_reservation
  ALTER COLUMN ready_expires_at SET NOT NULL;

ALTER TABLE destination_reservation
  ADD CONSTRAINT destination_reservation_phase7_ready_bounds
  CHECK (ready_expires_at > reserved_at),
  ADD CONSTRAINT destination_reservation_phase7_flow_bounds
  CHECK (flow_expires_at > reserved_at),
  ADD CONSTRAINT destination_reservation_phase7_ready_within_flow
  CHECK (ready_expires_at <= flow_expires_at),
  ADD CONSTRAINT destination_reservation_phase7_claim_after_offer
  CHECK (claimed_at IS NULL OR claimed_at >= reserved_at),
  ADD CONSTRAINT destination_reservation_phase7_claim_before_expiry
  CHECK (claimed_at IS NULL OR claimed_at < ready_expires_at),
  ADD CONSTRAINT destination_reservation_phase7_release_coherence
  CHECK ((released_at IS NULL) = (release_reason IS NULL)),
  ADD CONSTRAINT destination_reservation_phase7_release_after_offer
  CHECK (released_at IS NULL OR released_at >= reserved_at),
  ADD CONSTRAINT destination_reservation_phase7_release_reason
  CHECK (release_reason IN (
    'ready_claim_expired',
    'cancelled',
    'return_started',
    'completed',
    'destination_unavailable',
    'pass_terminal'
  )),
  ADD CONSTRAINT destination_reservation_phase7_destination_same_school
  FOREIGN KEY (tenant_id, organization_id, destination_id)
  REFERENCES destination (tenant_id, organization_id, id),
  ADD CONSTRAINT destination_reservation_phase7_pass_same_school
  FOREIGN KEY (tenant_id, organization_id, pass_id)
  REFERENCES pass (tenant_id, organization_id, id),
  ADD CONSTRAINT destination_reservation_phase7_policy_binding
  FOREIGN KEY (tenant_id, pass_id, policy_evaluation_id)
  REFERENCES policy_evaluation (tenant_id, pass_id, id);

-- 5. Harden queue_entry. entered_at marks when this queue attempt began;
-- flow_expires_at is the absolute deadline inherited across requeues;
-- released_at marks when the entry ceased being active.
DO $$
DECLARE
  fk record;
BEGIN
  FOR fk IN
    SELECT conname, conrelid::regclass AS table_name
    FROM pg_constraint
    WHERE contype = 'f'
      AND conrelid = 'queue_entry'::regclass
      AND array_length(conkey, 1) = 2
  LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', fk.table_name, fk.conname);
  END LOOP;
END $$;

ALTER TABLE queue_entry
  ADD COLUMN organization_id uuid NOT NULL,
  ADD COLUMN policy_evaluation_id uuid NOT NULL,
  ADD COLUMN flow_expires_at timestamptz NOT NULL,
  ADD COLUMN release_reason text;

ALTER TABLE queue_entry
  ADD CONSTRAINT queue_entry_phase7_flow_bounds
  CHECK (flow_expires_at > entered_at),
  ADD CONSTRAINT queue_entry_phase7_release_coherence
  CHECK ((released_at IS NULL) = (release_reason IS NULL)),
  ADD CONSTRAINT queue_entry_phase7_release_reason
  CHECK (release_reason IN (
    'promoted',
    'cancelled',
    'expired',
    'policy_changed',
    'destination_unavailable',
    'pass_terminal',
    'ready_requeue_replaced'
  )),
  ADD CONSTRAINT queue_entry_phase7_destination_same_school
  FOREIGN KEY (tenant_id, organization_id, destination_id)
  REFERENCES destination (tenant_id, organization_id, id),
  ADD CONSTRAINT queue_entry_phase7_pass_same_school
  FOREIGN KEY (tenant_id, organization_id, pass_id)
  REFERENCES pass (tenant_id, organization_id, id),
  ADD CONSTRAINT queue_entry_phase7_policy_binding
  FOREIGN KEY (tenant_id, pass_id, policy_evaluation_id)
  REFERENCES policy_evaluation (tenant_id, pass_id, id);
`;
