/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface AcademicSession {
  ends_on: string;
  id: Generated<string>;
  kind: string;
  name: string;
  organization_id: string;
  parent_id: string | null;
  starts_on: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface Account {
  created_at: Generated<string>;
  id: Generated<string>;
  person_id: string;
  session_revision: Generated<Int8>;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<string>;
}

export interface AuditEvent {
  action: string;
  actor_id: string | null;
  actor_kind: string;
  id: Generated<string>;
  metadata: Generated<Json>;
  occurred_at: Generated<string>;
  organization_id: string | null;
  outcome: string;
  request_id: string;
  target_id: string | null;
  target_kind: string;
  tenant_id: string;
}

export interface AuthIdentity {
  account_id: string;
  created_at: Generated<string>;
  email_snapshot: string | null;
  id: Generated<string>;
  issuer: string;
  provider_subject: string;
  tenant_id: string;
  updated_at: Generated<string>;
}

export interface AuthorizationGrant {
  account_id: string;
  created_at: Generated<string>;
  destination_id: string | null;
  id: Generated<string>;
  organization_id: string | null;
  role: string;
  scope_kind: string;
  section_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  valid_from: string | null;
  valid_until: string | null;
}

export interface CalendarDay {
  cycle_code: string | null;
  date: string;
  day_kind: string;
  id: Generated<string>;
  operational_note: string | null;
  organization_id: string;
  schedule_template_id: string | null;
  tenant_id: string;
}

export interface Course {
  code: string | null;
  id: Generated<string>;
  organization_id: string;
  status: Generated<string>;
  tenant_id: string;
  title: string;
}

export interface Destination {
  capacity: number | null;
  check_in_mode: Generated<string>;
  default_duration_seconds: number | null;
  display_name: string | null;
  id: Generated<string>;
  location_id: string;
  max_duration_seconds: number | null;
  organization_id: string;
  queue_enabled: Generated<boolean>;
  service_type: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface DestinationReservation {
  destination_id: string;
  expires_at: string | null;
  id: Generated<string>;
  pass_id: string;
  released_at: string | null;
  reserved_at: Generated<string>;
  tenant_id: string;
}

export interface ExternalReference {
  canonical_entity_id: string;
  entity_kind: string;
  external_id: string;
  external_object_type: string;
  id: Generated<string>;
  integration_id: string;
  last_seen_at: string | null;
  source_fingerprint: string | null;
  tenant_id: string;
}

export interface IdempotencyRecord {
  actor_account_id: string;
  command: string;
  created_at: Generated<string>;
  expires_at: string;
  id: Generated<string>;
  idempotency_key: string;
  request_fingerprint: string;
  response_body: Json;
  response_status: number;
  tenant_id: string;
}

export interface IncidentAffectedPass {
  incident_id: string;
  pass_id: string;
  pass_state_at_activation: string;
  tenant_id: string;
}

export interface IncidentPresenceReport {
  id: Generated<string>;
  incident_id: string;
  location_id: string;
  person_id: string;
  presence_state: string;
  reported_at: Generated<string>;
  reported_by_person_id: string;
  tenant_id: string;
}

export interface Integration {
  configuration: Generated<Json>;
  created_at: Generated<string>;
  id: Generated<string>;
  integration_type: string;
  name: string;
  organization_id: string | null;
  secret_ciphertext: Buffer | null;
  secret_key_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<string>;
}

export interface Location {
  code: string | null;
  created_at: Generated<string>;
  floor_label: string | null;
  id: Generated<string>;
  kind: string;
  name: string;
  organization_id: string;
  parent_location_id: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<string>;
}

export interface OperationalIncident {
  activated_at: Generated<string>;
  activated_by_person_id: string;
  ended_at: string | null;
  ended_by_person_id: string | null;
  id: Generated<string>;
  mode: string;
  operational_message: string | null;
  organization_id: string;
  tenant_id: string;
}

export interface Organization {
  created_at: Generated<string>;
  id: Generated<string>;
  kind: string;
  name: string;
  parent_id: string | null;
  slug: string;
  status: Generated<string>;
  tenant_id: string;
  time_zone: string | null;
  updated_at: Generated<string>;
}

export interface OrganizationMembership {
  affiliation: string;
  grade_level: string | null;
  id: Generated<string>;
  organization_id: string;
  person_id: string;
  status: Generated<string>;
  tenant_id: string;
  valid_from: string | null;
  valid_until: string | null;
}

export interface OutboxEvent {
  aggregate_id: string;
  aggregate_kind: string;
  attempt_count: Generated<number>;
  available_at: Generated<string>;
  event_type: string;
  id: Generated<string>;
  last_error: string | null;
  occurred_at: string;
  organization_id: string | null;
  payload: Json;
  published_at: string | null;
  tenant_id: string;
}

export interface Pass {
  created_at: Generated<string>;
  destination_id: string;
  expected_return_at: string | null;
  id: Generated<string>;
  lifecycle_state: string;
  organization_id: string;
  origin_location_id: string | null;
  origin_section_id: string | null;
  request_source: string;
  requested_at: Generated<string>;
  requested_by_person_id: string | null;
  return_location_id: string | null;
  revision: Generated<Int8>;
  scheduled_authorization_id: string | null;
  student_id: string;
  tenant_id: string;
  updated_at: Generated<string>;
}

export interface PassEvent {
  actor_integration_id: string | null;
  actor_kind: string;
  actor_person_id: string | null;
  event_type: string;
  id: Generated<string>;
  metadata: Generated<Json>;
  occurred_at: string;
  pass_id: string;
  sequence: Int8;
  tenant_id: string;
}

export interface PassOverride {
  category: string | null;
  decided_at: string | null;
  decided_by_person_id: string | null;
  decision: Generated<string>;
  evaluation_result_id: string;
  id: Generated<string>;
  pass_id: string;
  requested_at: Generated<string>;
  requested_by_person_id: string;
  tenant_id: string;
}

export interface Person {
  created_at: Generated<string>;
  display_name: string;
  family_name: string;
  given_name: string;
  id: Generated<string>;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<string>;
}

export interface PolicyEvaluation {
  decision: string;
  evaluated_at: Generated<string>;
  id: Generated<string>;
  pass_id: string;
  stage: string;
  tenant_id: string;
}

export interface PolicyEvaluationResult {
  evaluation_id: string;
  id: Generated<string>;
  outcome: string;
  override_mode: string;
  policy_rule_id: string;
  policy_rule_revision: number;
  reason_code: string;
  tenant_id: string;
}

export interface PolicyRule {
  configuration: Json;
  created_at: Generated<string>;
  enabled: Generated<boolean>;
  id: Generated<string>;
  name: string;
  organization_id: string;
  override_mode: string;
  priority: Generated<number>;
  revision: Generated<number>;
  rule_type: string;
  scope_destination_id: string | null;
  scope_kind: string;
  scope_organization_id: string | null;
  scope_section_id: string | null;
  tenant_id: string;
  updated_at: Generated<string>;
  valid_from: string | null;
  valid_until: string | null;
}

export interface QueueEntry {
  destination_id: string;
  entered_at: Generated<string>;
  id: Generated<string>;
  pass_id: string;
  priority: Generated<number>;
  released_at: string | null;
  tenant_id: string;
}

export interface ScheduleBlock {
  code: string;
  display_name: string;
  id: Generated<string>;
  kind: string;
  organization_id: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface ScheduledAuthorization {
  approval_mode: string;
  created_at: Generated<string>;
  created_by_person_id: string;
  destination_id: string;
  display_category: string | null;
  id: Generated<string>;
  organization_id: string;
  origin_location_id: string | null;
  origin_strategy: string;
  status: Generated<string>;
  student_id: string;
  tenant_id: string;
  updated_at: Generated<string>;
  valid_from: string;
  valid_until: string;
}

export interface ScheduleSlot {
  ends_at: string;
  id: Generated<string>;
  ordinal: number;
  organization_id: string;
  schedule_block_id: string;
  schedule_template_id: string;
  starts_at: string;
  tenant_id: string;
}

export interface ScheduleTemplate {
  id: Generated<string>;
  name: string;
  organization_id: string;
  status: Generated<string>;
  tenant_id: string;
}

export interface Section {
  academic_session_id: string;
  code: string | null;
  course_id: string | null;
  id: Generated<string>;
  organization_id: string;
  status: Generated<string>;
  tenant_id: string;
  title: string;
}

export interface SectionMeeting {
  cycle_code: string | null;
  effective_from: string | null;
  effective_until: string | null;
  id: Generated<string>;
  location_id: string | null;
  organization_id: string;
  schedule_block_id: string;
  section_id: string;
  tenant_id: string;
}

export interface SectionMembership {
  ends_on: string | null;
  id: Generated<string>;
  person_id: string;
  role: string;
  section_id: string;
  starts_on: string | null;
  status: Generated<string>;
  tenant_id: string;
}

export interface SyncRun {
  created_count: Generated<number>;
  error_summary: string | null;
  finished_at: string | null;
  id: Generated<string>;
  integration_id: string;
  outcome: Generated<string>;
  processed_count: Generated<number>;
  skipped_count: Generated<number>;
  started_at: Generated<string>;
  tenant_id: string;
  updated_count: Generated<number>;
}

export interface Tenant {
  created_at: Generated<string>;
  id: Generated<string>;
  name: string;
  status: Generated<string>;
  updated_at: Generated<string>;
}

export interface DB {
  academic_session: AcademicSession;
  account: Account;
  audit_event: AuditEvent;
  auth_identity: AuthIdentity;
  authorization_grant: AuthorizationGrant;
  calendar_day: CalendarDay;
  course: Course;
  destination: Destination;
  destination_reservation: DestinationReservation;
  external_reference: ExternalReference;
  idempotency_record: IdempotencyRecord;
  incident_affected_pass: IncidentAffectedPass;
  incident_presence_report: IncidentPresenceReport;
  integration: Integration;
  location: Location;
  operational_incident: OperationalIncident;
  organization: Organization;
  organization_membership: OrganizationMembership;
  outbox_event: OutboxEvent;
  pass: Pass;
  pass_event: PassEvent;
  pass_override: PassOverride;
  person: Person;
  policy_evaluation: PolicyEvaluation;
  policy_evaluation_result: PolicyEvaluationResult;
  policy_rule: PolicyRule;
  queue_entry: QueueEntry;
  schedule_block: ScheduleBlock;
  schedule_slot: ScheduleSlot;
  schedule_template: ScheduleTemplate;
  scheduled_authorization: ScheduledAuthorization;
  section: Section;
  section_meeting: SectionMeeting;
  section_membership: SectionMembership;
  sync_run: SyncRun;
  tenant: Tenant;
}
