/**
 * Canonical destination-category presentation registry.
 *
 * The database stores only safe product keys (`icon_key`, `tone_key`);
 * this module owns the curated set of valid keys. Adding a new icon or
 * tone is a code/config change here — never a migration — per the
 * destination-categories architecture. The web frontend keeps the single
 * centralized key -> component/class mapping; this module is the
 * server-side validation half and must stay in sync with it.
 */
export const DESTINATION_CATEGORY_ICON_KEYS = [
  'restroom',
  'shower',
  'soap',
  'towel',
  'door',
  'stairs',
  'parking',
  'lamp',
  'mirror',
  'building',
  'school',
  'house',
  'apartment',
  'city',
  'farm',
  'garage',
  'factory',
  'hotel',
  'store',
  'cafeteria',
  'gym_hall',
  'auditorium',
  'lab_room',
  'person',
  'teacher',
  'teaching',
  'doctor',
  'support',
  'coach',
  'baby',
  'professional',
  'teamwork',
  'graduation',
  'diploma',
  'certificate',
  'trophy',
  'medal',
  'star',
  'goal',
  'mascot',
  'crown',
  'book',
  'reading',
  'notebook',
  'note',
  'pencil',
  'desk',
  'backpack',
  'science',
  'calculator',
  'math',
  'pi',
  'infinity',
  'function',
  'plus',
  'minus',
  'divide',
  'equal',
  'abacus',
  'ruler',
  'triangle',
  'earth',
  'map',
  'location',
  'mappin',
  'directions',
  'history',
  'scroll',
  'writing',
  'art',
  'paint',
  'canvas',
  'bookshelf',
  'bookmark',
  'castle',
  'bridge',
  'road',
  'question',
  'info',
  'search_icon',
  'music',
  'microphone',
  'video',
  'camera',
  'tv',
  'projector',
  'game',
  'chess',
  'cards',
  'darts',
  'archery',
  'theater_magic',
  'fencing',
  'medical',
  'clinic',
  'medicine',
  'pill',
  'prescriptions',
  'thermometer',
  'bandage',
  'brain',
  'dna',
  'accessibility',
  'rest',
  'pillow',
  'gloves',
  'ambulance',
  'siren',
  'safety',
  'safety_vest',
  'hearing',
  'scale',
  'food',
  'culinary',
  'pizza',
  'sandwich',
  'bread',
  'cake',
  'candy',
  'coffee',
  'soda',
  'drink_cup',
  'water',
  'fork',
  'bread_knife',
  'spoon',
  'salad',
  'cooking_pot',
  'kettle',
  'fridge',
  'microwave',
  'oven',
  'blender',
  'whisk',
  'spatula',
  'napkins',
  'egg',
  'sports',
  'fitness',
  'running',
  'swimming',
  'bowling',
  'football',
  'biking',
  'camper',
  'campfire',
  'tent',
  'mountain',
  'beach',
  'island',
  'ferry',
  'anchor',
  'sailboat',
  'plane',
  'train',
  'journey',
  'travel',
  'sun',
  'moon',
  'sunset',
  'sunrise',
  'rainbow',
  'rain',
  'snow',
  'eclipse',
  'plant',
  'plant2',
  'snail',
  'feather',
  'bird',
  'fish',
  'cat',
  'paw',
  'gem',
  'diamond',
  'party',
  'gift',
  'fireworks',
  'sparkles',
  'lantern',
  'ticket',
  'flag',
  'balloons',
  'hoodie',
  'dress',
  'apron',
  'shirt',
  'shoes',
  'hat',
  'socks',
  'glasses',
  'briefcase',
  'folder',
  'archive',
  'news',
  'tag',
  'label',
  'discount',
  'percent',
  'contract',
  'key',
  'lock',
  'safe',
  'money',
  'bank',
  'cash',
  'savings',
  'tax',
  'receipt',
  'chart',
  'table',
  'layout',
  'calendar',
  'clock',
  'alarm',
  'bell',
  'timer',
  'refresh',
  'copy',
  'scissors',
  'mail',
  'mailbox',
  'package',
  'shopping',
  'card_payment',
  'box',
  'bucket',
  'jar',
  'cabinet',
  'chair',
  'technology',
  'keyboard',
  'mouse',
  'smartphone',
  'wifi',
  'robot',
  'plug',
  'solar',
  'battery',
  'fuel',
  'gauge',
  'hammer',
  'drill',
  'tape_measure',
  'thread',
  'cable',
  'brick',
  'logout',
  'generic',
  'chat',
] as const;

export type DestinationCategoryIconKey = (typeof DESTINATION_CATEGORY_ICON_KEYS)[number];

export const DESTINATION_CATEGORY_TONE_KEYS = [
  'aqua',
  'rose',
  'violet',
  'amber',
  'blue',
  'green',
  'slate',
  'neutral',
] as const;

export type DestinationCategoryToneKey = (typeof DESTINATION_CATEGORY_TONE_KEYS)[number];

export const DESTINATION_CATEGORY_SURFACES = ['primary', 'secondary', 'hidden'] as const;

export type DestinationCategorySurface = (typeof DESTINATION_CATEGORY_SURFACES)[number];

export const DESTINATION_CATEGORY_STATUSES = ['active', 'archived'] as const;

export type DestinationCategoryStatus = (typeof DESTINATION_CATEGORY_STATUSES)[number];

/**
 * Generic destination picker modes. `auto` chooses ItemGroup for a small
 * set and Combobox once the set is sufficiently large; `list` and `search`
 * force one presentation. Never branch on category names to pick UI.
 */
export const DESTINATION_CATEGORY_PICKER_MODES = ['auto', 'list', 'search'] as const;

export type DestinationCategoryPickerMode = (typeof DESTINATION_CATEGORY_PICKER_MODES)[number];

/** Destination count at or above which `auto` switches to search. */
export const DESTINATION_CATEGORY_AUTO_SEARCH_THRESHOLD = 8;

export function isDestinationCategoryPickerMode(
  value: string,
): value is DestinationCategoryPickerMode {
  return (DESTINATION_CATEGORY_PICKER_MODES as readonly string[]).includes(value);
}

/** Human-facing labels for admin selects; the wire values stay safe keys. */
export const DESTINATION_CATEGORY_ICON_LABELS: Record<DestinationCategoryIconKey, string> = {
  restroom: 'Restroom',
  shower: 'Shower',
  soap: 'Soap',
  towel: 'Towel',
  door: 'Door',
  stairs: 'Stairs',
  parking: 'Parking',
  lamp: 'Lamp',
  mirror: 'Mirror',
  building: 'Building',
  school: 'School',
  house: 'House',
  apartment: 'Apartment',
  city: 'City',
  farm: 'Farm',
  garage: 'Garage',
  factory: 'Factory',
  hotel: 'Hotel',
  store: 'Store',
  cafeteria: 'Cafeteria',
  gym_hall: 'Gymnasium',
  auditorium: 'Auditorium',
  lab_room: 'Laboratory',
  person: 'Person',
  teacher: 'Teacher',
  teaching: 'Teaching',
  doctor: 'Doctor',
  support: 'Support',
  coach: 'Coach',
  baby: 'Child care',
  professional: 'Professional',
  teamwork: 'Teamwork',
  graduation: 'Graduation',
  diploma: 'Diploma',
  certificate: 'Certificate',
  trophy: 'Trophy',
  medal: 'Medal',
  star: 'Star',
  goal: 'Goal',
  mascot: 'Mascot',
  crown: 'Crown',
  book: 'Book',
  reading: 'Reading',
  notebook: 'Notebook',
  note: 'Note',
  pencil: 'Pencil',
  desk: 'Desk',
  backpack: 'Backpack',
  science: 'Science',
  calculator: 'Calculator',
  math: 'Math',
  pi: 'Pi',
  infinity: 'Infinity',
  function: 'Function',
  plus: 'Plus',
  minus: 'Minus',
  divide: 'Divide',
  equal: 'Equal',
  abacus: 'Abacus',
  ruler: 'Ruler',
  triangle: 'Triangle',
  earth: 'Globe',
  map: 'Map',
  location: 'Location',
  mappin: 'Map pin',
  directions: 'Directions',
  history: 'History',
  scroll: 'Scroll',
  writing: 'Writing',
  art: 'Art',
  paint: 'Paint',
  canvas: 'Canvas',
  bookshelf: 'Bookshelf',
  bookmark: 'Bookmark',
  castle: 'Castle',
  bridge: 'Bridge',
  road: 'Road',
  question: 'Question',
  info: 'Information',
  search_icon: 'Search',
  music: 'Music',
  microphone: 'Microphone',
  video: 'Video',
  camera: 'Camera',
  tv: 'TV',
  projector: 'Projector',
  game: 'Games',
  chess: 'Chess',
  cards: 'Cards',
  darts: 'Darts',
  archery: 'Archery',
  theater_magic: 'Stage magic',
  fencing: 'Fencing',
  medical: 'Medical',
  clinic: 'Clinic',
  medicine: 'Medicine',
  pill: 'Pill',
  prescriptions: 'Prescriptions',
  thermometer: 'Thermometer',
  bandage: 'First aid',
  brain: 'Mind',
  dna: 'DNA',
  accessibility: 'Accessibility',
  rest: 'Rest',
  pillow: 'Pillow',
  gloves: 'Gloves',
  ambulance: 'Ambulance',
  siren: 'Siren',
  safety: 'Safety',
  safety_vest: 'Safety vest',
  hearing: 'Hearing',
  scale: 'Scale',
  food: 'Food',
  culinary: 'Culinary',
  pizza: 'Pizza',
  sandwich: 'Sandwich',
  bread: 'Bread',
  cake: 'Cake',
  candy: 'Candy',
  coffee: 'Coffee',
  soda: 'Soda',
  drink_cup: 'Drink cup',
  water: 'Water',
  fork: 'Fork',
  bread_knife: 'Kitchen knife',
  spoon: 'Spoon',
  salad: 'Salad',
  cooking_pot: 'Cooking',
  kettle: 'Kettle',
  fridge: 'Fridge',
  microwave: 'Microwave',
  oven: 'Oven',
  blender: 'Blender',
  whisk: 'Whisk',
  spatula: 'Spatula',
  napkins: 'Napkins',
  egg: 'Egg',
  sports: 'Sports',
  fitness: 'Fitness',
  running: 'Running',
  swimming: 'Swimming',
  bowling: 'Bowling',
  football: 'Football',
  biking: 'Biking',
  camper: 'Camping',
  campfire: 'Campfire',
  tent: 'Tent',
  mountain: 'Mountain',
  beach: 'Beach',
  island: 'Island',
  ferry: 'Ferry',
  anchor: 'Anchor',
  sailboat: 'Sailboat',
  plane: 'Plane',
  train: 'Train',
  journey: 'Route',
  travel: 'Travel',
  sun: 'Sun',
  moon: 'Moon',
  sunset: 'Sunset',
  sunrise: 'Sunrise',
  rainbow: 'Rainbow',
  rain: 'Rain',
  snow: 'Snow',
  eclipse: 'Eclipse',
  plant: 'Plant',
  plant2: 'Seedling',
  snail: 'Snail',
  feather: 'Feather',
  bird: 'Bird',
  fish: 'Fish',
  cat: 'Cat',
  paw: 'Paw',
  gem: 'Gem',
  diamond: 'Diamond',
  party: 'Party',
  gift: 'Gift',
  fireworks: 'Fireworks',
  sparkles: 'Sparkles',
  lantern: 'Lantern',
  ticket: 'Ticket',
  flag: 'Flag',
  balloons: 'Balloons',
  hoodie: 'Hoodie',
  dress: 'Dress',
  apron: 'Apron',
  shirt: 'Shirt',
  shoes: 'Shoes',
  hat: 'Hat',
  socks: 'Socks',
  glasses: 'Glasses',
  briefcase: 'Briefcase',
  folder: 'Folder',
  archive: 'Archive',
  news: 'News',
  tag: 'Tag',
  label: 'Label',
  discount: 'Discount',
  percent: 'Percent',
  contract: 'Contract',
  key: 'Key',
  lock: 'Lock',
  safe: 'Safe',
  money: 'Money',
  bank: 'Bank',
  cash: 'Cash',
  savings: 'Savings',
  tax: 'Tax',
  receipt: 'Receipt',
  chart: 'Chart',
  table: 'Table',
  layout: 'Layout',
  calendar: 'Calendar',
  clock: 'Clock',
  alarm: 'Alarm',
  bell: 'Bell',
  timer: 'Timer',
  refresh: 'Refresh',
  copy: 'Copy',
  scissors: 'Scissors',
  mail: 'Mail',
  mailbox: 'Mailbox',
  package: 'Package',
  shopping: 'Shopping bag',
  card_payment: 'Card payment',
  box: 'Box',
  bucket: 'Bucket',
  jar: 'Jar',
  cabinet: 'Cabinet',
  chair: 'Chair',
  technology: 'Technology',
  keyboard: 'Keyboard',
  mouse: 'Mouse',
  smartphone: 'Phone',
  wifi: 'Wi-Fi',
  robot: 'Robotics',
  plug: 'Plug',
  solar: 'Solar',
  battery: 'Battery',
  fuel: 'Fuel',
  gauge: 'Gauge',
  hammer: 'Hammer',
  drill: 'Drill',
  tape_measure: 'Tape measure',
  thread: 'Thread',
  cable: 'Cable',
  brick: 'Brick',
  logout: 'Log out',
  generic: 'More (grid)',
  chat: 'Conversation',
};

export const DESTINATION_CATEGORY_TONE_LABELS: Record<DestinationCategoryToneKey, string> = {
  aqua: 'Aqua',
  rose: 'Rose',
  violet: 'Violet',
  amber: 'Amber',
  blue: 'Blue',
  green: 'Green',
  slate: 'Slate',
  neutral: 'Neutral',
};

export function isDestinationCategoryIconKey(value: string): value is DestinationCategoryIconKey {
  return (DESTINATION_CATEGORY_ICON_KEYS as readonly string[]).includes(value);
}

export function isDestinationCategoryToneKey(value: string): value is DestinationCategoryToneKey {
  return (DESTINATION_CATEGORY_TONE_KEYS as readonly string[]).includes(value);
}

export function isDestinationCategorySurface(value: string): value is DestinationCategorySurface {
  return (DESTINATION_CATEGORY_SURFACES as readonly string[]).includes(value);
}
