import type { ComponentProps } from 'react';
import type { HugeiconsIcon } from '@hugeicons/react';
import {
  AbacusIcon,
  AlarmClockIcon,
  AmbulanceIcon,
  AnchorIcon,
  ApartmentIcon,
  ApronIcon,
  ArcherIcon,
  Archive01Icon,
  ArtboardIcon,
  Baby01Icon,
  Backpack01Icon,
  BalloonsIcon,
  BandageIcon,
  BankIcon,
  BarnsIcon,
  BatteryIcon,
  Beach02Icon,
  BedIcon,
  BellIcon,
  BikeIcon,
  BirdIcon,
  BlenderIcon,
  Book01Icon,
  Bookmark01Icon,
  Bookshelf01Icon,
  BowlingIcon,
  BoxIcon,
  Brain01Icon,
  Bread01Icon,
  BrickWallIcon,
  Briefcase01Icon,
  BridgeIcon,
  BubbleChatIcon,
  BucketIcon,
  Cabinet01Icon,
  CakeIcon,
  CalculatorIcon,
  Calendar02Icon,
  Camera02Icon,
  CamperIcon,
  CampfireIcon,
  CandyIcon,
  CanvasIcon,
  Cards01Icon,
  Cash01Icon,
  Castle01Icon,
  CatIcon,
  Certificate01Icon,
  Chair01Icon,
  ChartIcon,
  ChefIcon,
  Chess01Icon,
  City01Icon,
  ClinicIcon,
  Clock02Icon,
  Coffee01Icon,
  ContractsIcon,
  Copy02Icon,
  CreditCardIcon,
  CrownIcon,
  CupSodaIcon,
  DartIcon,
  Desk01Icon,
  DiamondIcon,
  DiplomaIcon,
  DiscountIcon,
  DivideIcon,
  Dna01Icon,
  Doctor01Icon,
  Door01Icon,
  Dress01Icon,
  DrillIcon,
  DropletIcon,
  Dumbbell01Icon,
  EarthIcon,
  EclipseIcon,
  EggIcon,
  EqualIcon,
  Factory01Icon,
  FeatherIcon,
  FerryBoatIcon,
  FireworksIcon,
  FishIcon,
  Flag02Icon,
  Folder01Icon,
  FootballIcon,
  ForkIcon,
  FridgeIcon,
  FuelIcon,
  FunctionIcon,
  GameController01Icon,
  GarageIcon,
  GaugeIcon,
  GavelIcon,
  GemIcon,
  GiftIcon,
  GlassesIcon,
  GloveIcon,
  GoalIcon,
  GraduationCapIcon,
  GridIcon,
  GymnasticIcon,
  HammerIcon,
  HatIcon,
  HistoryIcon,
  HoodieIcon,
  Hotel01Icon,
  House01Icon,
  Infinity02Icon,
  InfoIcon,
  IslandIcon,
  JarIcon,
  KettleIcon,
  Key02Icon,
  KeyboardIcon,
  KnifeBreadIcon,
  KnightShieldIcon,
  LabelIcon,
  Lamp02Icon,
  LanternIcon,
  LaptopIcon,
  Layout01Icon,
  LibraryIcon,
  LifebuoyIcon,
  Location02Icon,
  LockIcon,
  Logout02Icon,
  Mail02Icon,
  Mailbox01Icon,
  MapIcon,
  MapPinIcon,
  MathIcon,
  Medal01Icon,
  Medicine01Icon,
  Mic02Icon,
  MicrowaveIcon,
  MicroscopeIcon,
  MinusIcon,
  MirrorIcon,
  Money02Icon,
  MoonIcon,
  MountainIcon,
  Mouse01Icon,
  MusicNote01Icon,
  Napkins01Icon,
  Navigation02Icon,
  News01Icon,
  Notebook01Icon,
  NoteIcon,
  OfficeIcon,
  OvenIcon,
  Package01Icon,
  PaintBoardIcon,
  ParkingAreaCircleIcon,
  PartyIcon,
  PawPrintIcon,
  PencilIcon,
  PercentIcon,
  PiIcon,
  PiggyBankIcon,
  PillBottleIcon,
  PillIcon,
  PillowIcon,
  Pizza01Icon,
  PlaneIcon,
  Plant01Icon,
  Plug01Icon,
  PlusIcon,
  Pot01Icon,
  Presentation02Icon,
  ProjectorIcon,
  QuestionIcon,
  QuillWrite01Icon,
  RainbowIcon,
  RainIcon,
  ReceiptIcon,
  RefreshIcon,
  RestaurantIcon,
  Road01Icon,
  Robot01Icon,
  RunningShoesIcon,
  Route01Icon,
  RulerIcon,
  SafeIcon,
  SailboatIcon,
  SaladIcon,
  ScaleIcon,
  SandwichIcon,
  SchoolIcon,
  ScissorsIcon,
  ScrollIcon,
  Search02Icon,
  Shield01Icon,
  Shirt01Icon,
  ShoesIcon,
  ShoppingBag01Icon,
  SirenIcon,
  ShowerHeadIcon,
  SmartPhone01Icon,
  SnailIcon,
  SnowIcon,
  SoapDispenserDropletIcon,
  SocksIcon,
  SodaCanIcon,
  SolarEnergyIcon,
  SpatulaIcon,
  SparklesIcon,
  SpoonIcon,
  SproutIcon,
  Stairs01Icon,
  StarIcon,
  StethoscopeIcon,
  Store02Icon,
  Sun01Icon,
  SunriseIcon,
  SunsetIcon,
  SwimmingIcon,
  Sword01Icon,
  Table02Icon,
  Tag02Icon,
  TapeMeasureIcon,
  TaxiIcon,
  TeacherIcon,
  TeachingIcon,
  TeamWorkIcon,
  Telescope01Icon,
  TentIcon,
  ThermometerIcon,
  ThreadIcon,
  Ticket01Icon,
  TieIcon,
  Timer02Icon,
  Toilet02Icon,
  TowelsIcon,
  Train01Icon,
  TravelBagIcon,
  Triangle01Icon,
  TrophyIcon,
  Tv02Icon,
  UserIcon,
  VestIcon,
  Video01Icon,
  WandIcon,
  WhiskIcon,
  WheelchairIcon,
  WhistleIcon,
  Wifi01Icon,
  YogaBallIcon,
} from '@hugeicons/core-free-icons';
import { cva } from 'class-variance-authority';

/**
 * Single centralized destination-category presentation registry.
 *
 * The server persists only safe product keys (`iconKey`, `toneKey`); this
 * module is the one place that maps those keys to Hugeicons and
 * Maia-compatible classes. Admin and student code must both use it — never
 * a second copy of the map. Unknown keys fall back to the generic
 * presentation so a future server key never breaks the launcher.
 */
export type CategoryIcon = ComponentProps<typeof HugeiconsIcon>['icon'];

export interface CategoryIconDefinition {
  /** Persisted product key. Never rename a shipped key. */
  key: string;
  /** Human label shown in the picker. */
  label: string;
  /** Group heading used by the picker's ComboboxGroup. */
  group: string;
  /** Search aliases: alternative words that should match this icon. */
  aliases: readonly string[];
  icon: CategoryIcon;
}

/**
 * Curated school-relevant icon registry. Named Hugeicons imports only —
 * never a wildcard import, never thousands of eager icons, never arbitrary
 * SVG. Every entry resolves through `iconForCategoryKey` so admin and
 * student presentation stay consistent.
 */
export const CATEGORY_ICON_REGISTRY: readonly CategoryIconDefinition[] = [
  // Facilities
  {
    key: 'restroom',
    label: 'Restroom',
    group: 'Facilities',
    aliases: ['bathroom', 'restroom', 'toilet', 'lavatory', 'wc'],
    icon: Toilet02Icon,
  },
  {
    key: 'shower',
    label: 'Shower',
    group: 'Facilities',
    aliases: ['shower', 'locker room', 'pool', 'gym'],
    icon: ShowerHeadIcon,
  },
  {
    key: 'soap',
    label: 'Soap',
    group: 'Facilities',
    aliases: ['soap', 'wash', 'hygiene', 'bathroom'],
    icon: SoapDispenserDropletIcon,
  },
  {
    key: 'towel',
    label: 'Towel',
    group: 'Facilities',
    aliases: ['towel', 'pool', 'gym', 'shower', 'aquatics'],
    icon: TowelsIcon,
  },
  {
    key: 'door',
    label: 'Door',
    group: 'Facilities',
    aliases: ['door', 'entrance', 'exit', 'enter'],
    icon: Door01Icon,
  },
  {
    key: 'stairs',
    label: 'Stairs',
    group: 'Facilities',
    aliases: ['stairs', 'steps', 'stairwell', 'access', 'elevator', 'lift'],
    icon: Stairs01Icon,
  },
  {
    key: 'parking',
    label: 'Parking',
    group: 'Facilities',
    aliases: ['parking', 'lot', 'cars', 'drop off', 'pickup'],
    icon: ParkingAreaCircleIcon,
  },
  {
    key: 'lamp',
    label: 'Lamp',
    group: 'Facilities',
    aliases: ['lamp', 'light', 'reading'],
    icon: Lamp02Icon,
  },
  {
    key: 'mirror',
    label: 'Mirror',
    group: 'Facilities',
    aliases: ['mirror', 'drama', 'reflection', 'bathroom'],
    icon: MirrorIcon,
  },
  // Places
  {
    key: 'building',
    label: 'Building',
    group: 'Places',
    aliases: ['building', 'office', 'administration', 'principal', 'main office'],
    icon: OfficeIcon,
  },
  {
    key: 'school',
    label: 'School',
    group: 'Places',
    aliases: ['school', 'campus', 'education'],
    icon: SchoolIcon,
  },
  {
    key: 'house',
    label: 'House',
    group: 'Places',
    aliases: ['house', 'home', 'residence', 'main'],
    icon: House01Icon,
  },
  {
    key: 'apartment',
    label: 'Apartment',
    group: 'Places',
    aliases: ['apartment', 'residence', 'home'],
    icon: ApartmentIcon,
  },
  {
    key: 'city',
    label: 'City',
    group: 'Places',
    aliases: ['city', 'downtown', 'urban', 'field trip'],
    icon: City01Icon,
  },
  {
    key: 'farm',
    label: 'Farm',
    group: 'Places',
    aliases: ['barn', 'farm', 'agriculture'],
    icon: BarnsIcon,
  },
  {
    key: 'garage',
    label: 'Garage',
    group: 'Places',
    aliases: ['garage', 'auto', 'cars', 'shop'],
    icon: GarageIcon,
  },
  {
    key: 'factory',
    label: 'Factory',
    group: 'Places',
    aliases: ['factory', 'industry', 'careers', 'manufacturing'],
    icon: Factory01Icon,
  },
  {
    key: 'hotel',
    label: 'Hotel',
    group: 'Places',
    aliases: ['hotel', 'travel', 'field trip'],
    icon: Hotel01Icon,
  },
  {
    key: 'store',
    label: 'Store',
    group: 'Places',
    aliases: ['store', 'shop', 'school store', 'spirit wear'],
    icon: Store02Icon,
  },
  {
    key: 'cafeteria',
    label: 'Cafeteria',
    group: 'Places',
    aliases: ['cafeteria', 'cafe', 'lunchroom', 'commons'],
    icon: RestaurantIcon,
  },
  {
    key: 'gym_hall',
    label: 'Gymnasium',
    group: 'Places',
    aliases: ['gym', 'gymnasium', 'field house', 'arena'],
    icon: GymnasticIcon,
  },
  {
    key: 'auditorium',
    label: 'Auditorium',
    group: 'Places',
    aliases: ['auditorium', 'assembly', 'stage', 'presentation'],
    icon: Presentation02Icon,
  },
  {
    key: 'lab_room',
    label: 'Laboratory',
    group: 'Places',
    aliases: ['lab', 'laboratory', 'science room'],
    icon: MicroscopeIcon,
  },
  // People and roles
  {
    key: 'person',
    label: 'Person',
    group: 'People',
    aliases: ['person', 'user', 'individual'],
    icon: UserIcon,
  },
  {
    key: 'teacher',
    label: 'Teacher',
    group: 'People',
    aliases: ['teacher', 'staff', 'classroom', 'mentor', 'professor', 'instructor'],
    icon: TeacherIcon,
  },
  {
    key: 'teaching',
    label: 'Teaching',
    group: 'People',
    aliases: ['teaching', 'instruction', 'lesson'],
    icon: TeachingIcon,
  },
  {
    key: 'doctor',
    label: 'Doctor',
    group: 'People',
    aliases: ['doctor', 'physician', 'health', 'medical'],
    icon: Doctor01Icon,
  },
  {
    key: 'support',
    label: 'Support',
    group: 'People',
    aliases: ['support', 'help', 'guidance', 'counseling', 'counselor'],
    icon: LifebuoyIcon,
  },
  {
    key: 'coach',
    label: 'Coach',
    group: 'People',
    aliases: ['coach', 'whistle', 'sports', 'referee', 'pe'],
    icon: WhistleIcon,
  },
  {
    key: 'baby',
    label: 'Child care',
    group: 'People',
    aliases: ['baby', 'child care', 'nursery', 'toddler'],
    icon: Baby01Icon,
  },
  {
    key: 'professional',
    label: 'Professional',
    group: 'People',
    aliases: ['tie', 'formal', 'professional', 'dress', 'office'],
    icon: TieIcon,
  },
  {
    key: 'teamwork',
    label: 'Teamwork',
    group: 'People',
    aliases: ['team', 'teamwork', 'group', 'collaborate'],
    icon: TeamWorkIcon,
  },
  {
    key: 'graduation',
    label: 'Graduation',
    group: 'People',
    aliases: ['graduation', 'graduate', 'commencement'],
    icon: GraduationCapIcon,
  },
  {
    key: 'diploma',
    label: 'Diploma',
    group: 'People',
    aliases: ['diploma', 'degree'],
    icon: DiplomaIcon,
  },
  {
    key: 'certificate',
    label: 'Certificate',
    group: 'People',
    aliases: ['certificate', 'award', 'achievement'],
    icon: Certificate01Icon,
  },
  {
    key: 'trophy',
    label: 'Trophy',
    group: 'People',
    aliases: ['trophy', 'champion', 'winner', 'prize'],
    icon: TrophyIcon,
  },
  {
    key: 'medal',
    label: 'Medal',
    group: 'People',
    aliases: ['medal', 'honor', 'award'],
    icon: Medal01Icon,
  },
  {
    key: 'star',
    label: 'Star',
    group: 'People',
    aliases: ['star', 'excellent', 'favorite'],
    icon: StarIcon,
  },
  {
    key: 'goal',
    label: 'Goal',
    group: 'People',
    aliases: ['goal', 'target', 'objective'],
    icon: GoalIcon,
  },
  {
    key: 'mascot',
    label: 'Mascot',
    group: 'People',
    aliases: ['mascot', 'knight', 'shield', 'spirit'],
    icon: KnightShieldIcon,
  },
  {
    key: 'crown',
    label: 'Crown',
    group: 'People',
    aliases: ['crown', 'royal', 'prom', 'homecoming'],
    icon: CrownIcon,
  },
  // Academics
  {
    key: 'book',
    label: 'Book',
    group: 'Academics',
    aliases: ['book', 'library', 'reading', 'media'],
    icon: LibraryIcon,
  },
  {
    key: 'reading',
    label: 'Reading',
    group: 'Academics',
    aliases: ['reading', 'book', 'novel', 'literature'],
    icon: Book01Icon,
  },
  {
    key: 'notebook',
    label: 'Notebook',
    group: 'Academics',
    aliases: ['notebook', 'notes', 'journal'],
    icon: Notebook01Icon,
  },
  {
    key: 'note',
    label: 'Note',
    group: 'Academics',
    aliases: ['note', 'memo', 'reminder'],
    icon: NoteIcon,
  },
  {
    key: 'pencil',
    label: 'Pencil',
    group: 'Academics',
    aliases: ['pencil', 'write', 'draw'],
    icon: PencilIcon,
  },
  {
    key: 'desk',
    label: 'Desk',
    group: 'Academics',
    aliases: ['desk', 'classroom', 'study'],
    icon: Desk01Icon,
  },
  {
    key: 'backpack',
    label: 'Backpack',
    group: 'Academics',
    aliases: ['backpack', 'bag', 'supplies'],
    icon: Backpack01Icon,
  },
  {
    key: 'science',
    label: 'Science',
    group: 'Academics',
    aliases: ['science', 'telescope', 'astronomy', 'space'],
    icon: Telescope01Icon,
  },
  {
    key: 'calculator',
    label: 'Calculator',
    group: 'Academics',
    aliases: ['calculator', 'math', 'arithmetic'],
    icon: CalculatorIcon,
  },
  {
    key: 'math',
    label: 'Math',
    group: 'Academics',
    aliases: ['math', 'mathematics', 'numbers', 'algebra'],
    icon: MathIcon,
  },
  {
    key: 'pi',
    label: 'Pi',
    group: 'Academics',
    aliases: ['pi', 'geometry', 'math'],
    icon: PiIcon,
  },
  {
    key: 'infinity',
    label: 'Infinity',
    group: 'Academics',
    aliases: ['infinity', 'endless', 'math'],
    icon: Infinity02Icon,
  },
  {
    key: 'function',
    label: 'Function',
    group: 'Academics',
    aliases: ['function', 'algebra', 'math', 'graph'],
    icon: FunctionIcon,
  },
  {
    key: 'plus',
    label: 'Plus',
    group: 'Academics',
    aliases: ['plus', 'add', 'more', 'positive'],
    icon: PlusIcon,
  },
  {
    key: 'minus',
    label: 'Minus',
    group: 'Academics',
    aliases: ['minus', 'subtract', 'less'],
    icon: MinusIcon,
  },
  {
    key: 'divide',
    label: 'Divide',
    group: 'Academics',
    aliases: ['divide', 'division', 'math'],
    icon: DivideIcon,
  },
  {
    key: 'equal',
    label: 'Equal',
    group: 'Academics',
    aliases: ['equal', 'equals', 'math'],
    icon: EqualIcon,
  },
  {
    key: 'abacus',
    label: 'Abacus',
    group: 'Academics',
    aliases: ['abacus', 'counting', 'math'],
    icon: AbacusIcon,
  },
  {
    key: 'ruler',
    label: 'Ruler',
    group: 'Academics',
    aliases: ['ruler', 'measure', 'geometry'],
    icon: RulerIcon,
  },
  {
    key: 'triangle',
    label: 'Triangle',
    group: 'Academics',
    aliases: ['triangle', 'shape', 'geometry'],
    icon: Triangle01Icon,
  },
  {
    key: 'earth',
    label: 'Globe',
    group: 'Academics',
    aliases: ['globe', 'earth', 'world', 'geography'],
    icon: EarthIcon,
  },
  {
    key: 'map',
    label: 'Map',
    group: 'Academics',
    aliases: ['map', 'geography', 'atlas'],
    icon: MapIcon,
  },
  {
    key: 'location',
    label: 'Location',
    group: 'Academics',
    aliases: ['location', 'place', 'room'],
    icon: Location02Icon,
  },
  {
    key: 'mappin',
    label: 'Map pin',
    group: 'Academics',
    aliases: ['pin', 'directions', 'find', 'map'],
    icon: MapPinIcon,
  },
  {
    key: 'directions',
    label: 'Directions',
    group: 'Academics',
    aliases: ['directions', 'navigation', 'wayfinding'],
    icon: Navigation02Icon,
  },
  {
    key: 'history',
    label: 'History',
    group: 'Academics',
    aliases: ['history', 'past', 'social studies'],
    icon: HistoryIcon,
  },
  {
    key: 'scroll',
    label: 'Scroll',
    group: 'Academics',
    aliases: ['scroll', 'document', 'history'],
    icon: ScrollIcon,
  },
  {
    key: 'writing',
    label: 'Writing',
    group: 'Academics',
    aliases: ['quill', 'writing', 'poetry', 'creative'],
    icon: QuillWrite01Icon,
  },
  {
    key: 'art',
    label: 'Art',
    group: 'Academics',
    aliases: ['art', 'design', 'drawing', 'creative'],
    icon: ArtboardIcon,
  },
  {
    key: 'paint',
    label: 'Paint',
    group: 'Academics',
    aliases: ['paint', 'art', 'creative'],
    icon: PaintBoardIcon,
  },
  {
    key: 'canvas',
    label: 'Canvas',
    group: 'Academics',
    aliases: ['canvas', 'art', 'paint'],
    icon: CanvasIcon,
  },
  {
    key: 'bookshelf',
    label: 'Bookshelf',
    group: 'Academics',
    aliases: ['bookshelf', 'books', 'library'],
    icon: Bookshelf01Icon,
  },
  {
    key: 'bookmark',
    label: 'Bookmark',
    group: 'Academics',
    aliases: ['bookmark', 'save', 'mark'],
    icon: Bookmark01Icon,
  },
  {
    key: 'castle',
    label: 'Castle',
    group: 'Academics',
    aliases: ['castle', 'history', 'medieval'],
    icon: Castle01Icon,
  },
  {
    key: 'bridge',
    label: 'Bridge',
    group: 'Academics',
    aliases: ['bridge', 'engineering', 'connection'],
    icon: BridgeIcon,
  },
  {
    key: 'road',
    label: 'Road',
    group: 'Academics',
    aliases: ['road', 'street', 'drivers ed'],
    icon: Road01Icon,
  },
  {
    key: 'question',
    label: 'Question',
    group: 'Academics',
    aliases: ['question', 'ask', 'help', 'faq'],
    icon: QuestionIcon,
  },
  {
    key: 'info',
    label: 'Information',
    group: 'Academics',
    aliases: ['information', 'info', 'details', 'help'],
    icon: InfoIcon,
  },
  {
    key: 'search_icon',
    label: 'Search',
    group: 'Academics',
    aliases: ['search', 'find', 'lookup', 'magnifier'],
    icon: Search02Icon,
  },
  // Arts and media
  {
    key: 'music',
    label: 'Music',
    group: 'Arts',
    aliases: ['music', 'band', 'choir', 'orchestra'],
    icon: MusicNote01Icon,
  },
  {
    key: 'microphone',
    label: 'Microphone',
    group: 'Arts',
    aliases: ['microphone', 'mic', 'speech', 'audio'],
    icon: Mic02Icon,
  },
  {
    key: 'video',
    label: 'Video',
    group: 'Arts',
    aliases: ['video', 'film', 'media', 'production'],
    icon: Video01Icon,
  },
  {
    key: 'camera',
    label: 'Camera',
    group: 'Arts',
    aliases: ['camera', 'photo', 'photography', 'yearbook'],
    icon: Camera02Icon,
  },
  {
    key: 'tv',
    label: 'TV',
    group: 'Arts',
    aliases: ['tv', 'television', 'display', 'announcements'],
    icon: Tv02Icon,
  },
  {
    key: 'projector',
    label: 'Projector',
    group: 'Arts',
    aliases: ['projector', 'av', 'assembly'],
    icon: ProjectorIcon,
  },
  {
    key: 'game',
    label: 'Games',
    group: 'Arts',
    aliases: ['game', 'gaming', 'controller', 'esports'],
    icon: GameController01Icon,
  },
  {
    key: 'chess',
    label: 'Chess',
    group: 'Arts',
    aliases: ['chess', 'club', 'strategy'],
    icon: Chess01Icon,
  },
  {
    key: 'cards',
    label: 'Cards',
    group: 'Arts',
    aliases: ['cards', 'games', 'club'],
    icon: Cards01Icon,
  },
  {
    key: 'darts',
    label: 'Darts',
    group: 'Arts',
    aliases: ['darts', 'target', 'aim', 'game'],
    icon: DartIcon,
  },
  {
    key: 'archery',
    label: 'Archery',
    group: 'Arts',
    aliases: ['archery', 'bow', 'target'],
    icon: ArcherIcon,
  },
  {
    key: 'theater_magic',
    label: 'Stage magic',
    group: 'Arts',
    aliases: ['magic', 'wand', 'theater', 'creativity'],
    icon: WandIcon,
  },
  {
    key: 'fencing',
    label: 'Fencing',
    group: 'Arts',
    aliases: ['sword', 'fencing', 'theater', 'history'],
    icon: Sword01Icon,
  },
  // Health and wellness
  {
    key: 'medical',
    label: 'Medical',
    group: 'Health',
    aliases: ['medical', 'nurse', 'health', 'clinic', 'doctor'],
    icon: StethoscopeIcon,
  },
  {
    key: 'clinic',
    label: 'Clinic',
    group: 'Health',
    aliases: ['clinic', 'health center', 'doctor office'],
    icon: ClinicIcon,
  },
  {
    key: 'medicine',
    label: 'Medicine',
    group: 'Health',
    aliases: ['medicine', 'prescription', 'pharmacy'],
    icon: Medicine01Icon,
  },
  {
    key: 'pill',
    label: 'Pill',
    group: 'Health',
    aliases: ['pill', 'medication', 'prescription'],
    icon: PillIcon,
  },
  {
    key: 'prescriptions',
    label: 'Prescriptions',
    group: 'Health',
    aliases: ['bottle', 'prescription', 'pills', 'pharmacy'],
    icon: PillBottleIcon,
  },
  {
    key: 'thermometer',
    label: 'Thermometer',
    group: 'Health',
    aliases: ['thermometer', 'temperature', 'fever'],
    icon: ThermometerIcon,
  },
  {
    key: 'bandage',
    label: 'First aid',
    group: 'Health',
    aliases: ['bandage', 'first aid', 'injury'],
    icon: BandageIcon,
  },
  {
    key: 'brain',
    label: 'Mind',
    group: 'Health',
    aliases: ['brain', 'mind', 'psychology', 'thinking'],
    icon: Brain01Icon,
  },
  {
    key: 'dna',
    label: 'DNA',
    group: 'Health',
    aliases: ['dna', 'genetics', 'biology'],
    icon: Dna01Icon,
  },
  {
    key: 'accessibility',
    label: 'Accessibility',
    group: 'Health',
    aliases: ['wheelchair', 'accessibility', 'accessible'],
    icon: WheelchairIcon,
  },
  {
    key: 'rest',
    label: 'Rest',
    group: 'Health',
    aliases: ['bed', 'rest', 'sick', 'nurse office'],
    icon: BedIcon,
  },
  {
    key: 'pillow',
    label: 'Pillow',
    group: 'Health',
    aliases: ['pillow', 'rest', 'sleep'],
    icon: PillowIcon,
  },
  {
    key: 'gloves',
    label: 'Gloves',
    group: 'Health',
    aliases: ['gloves', 'safety', 'lab', 'nurse'],
    icon: GloveIcon,
  },
  {
    key: 'ambulance',
    label: 'Ambulance',
    group: 'Health',
    aliases: ['ambulance', 'emergency'],
    icon: AmbulanceIcon,
  },
  {
    key: 'siren',
    label: 'Siren',
    group: 'Health',
    aliases: ['siren', 'emergency', 'drill', 'alarm'],
    icon: SirenIcon,
  },
  {
    key: 'safety',
    label: 'Safety',
    group: 'Health',
    aliases: ['shield', 'safety', 'security', 'protection'],
    icon: Shield01Icon,
  },
  {
    key: 'safety_vest',
    label: 'Safety vest',
    group: 'Health',
    aliases: ['vest', 'safety', 'crossing', 'construction'],
    icon: VestIcon,
  },
  {
    key: 'hearing',
    label: 'Hearing',
    group: 'Health',
    aliases: ['gavel', 'discipline', 'hearing', 'justice'],
    icon: GavelIcon,
  },
  {
    key: 'scale',
    label: 'Scale',
    group: 'Health',
    aliases: ['scale', 'weigh', 'measure', 'science'],
    icon: ScaleIcon,
  },
  // Food and nutrition
  {
    key: 'food',
    label: 'Food',
    group: 'Food',
    aliases: ['food', 'lunch', 'cafeteria', 'restaurant', 'meal'],
    icon: RestaurantIcon,
  },
  {
    key: 'culinary',
    label: 'Culinary',
    group: 'Food',
    aliases: ['chef', 'cooking', 'culinary', 'kitchen'],
    icon: ChefIcon,
  },
  {
    key: 'pizza',
    label: 'Pizza',
    group: 'Food',
    aliases: ['pizza', 'lunch', 'food'],
    icon: Pizza01Icon,
  },
  {
    key: 'sandwich',
    label: 'Sandwich',
    group: 'Food',
    aliases: ['sandwich', 'lunch', 'deli'],
    icon: SandwichIcon,
  },
  {
    key: 'bread',
    label: 'Bread',
    group: 'Food',
    aliases: ['bread', 'bakery', 'lunch'],
    icon: Bread01Icon,
  },
  {
    key: 'cake',
    label: 'Cake',
    group: 'Food',
    aliases: ['cake', 'birthday', 'celebration'],
    icon: CakeIcon,
  },
  {
    key: 'candy',
    label: 'Candy',
    group: 'Food',
    aliases: ['candy', 'sweets', 'treat'],
    icon: CandyIcon,
  },
  {
    key: 'coffee',
    label: 'Coffee',
    group: 'Food',
    aliases: ['coffee', 'drink', 'cafe'],
    icon: Coffee01Icon,
  },
  {
    key: 'soda',
    label: 'Soda',
    group: 'Food',
    aliases: ['soda', 'drink', 'can'],
    icon: SodaCanIcon,
  },
  {
    key: 'drink_cup',
    label: 'Drink cup',
    group: 'Food',
    aliases: ['cup', 'drink', 'soda'],
    icon: CupSodaIcon,
  },
  {
    key: 'water',
    label: 'Water',
    group: 'Food',
    aliases: ['water', 'drink', 'fountain', 'bottle'],
    icon: DropletIcon,
  },
  {
    key: 'fork',
    label: 'Fork',
    group: 'Food',
    aliases: ['fork', 'utensils', 'lunch'],
    icon: ForkIcon,
  },
  {
    key: 'bread_knife',
    label: 'Kitchen knife',
    group: 'Food',
    aliases: ['knife', 'cutting', 'culinary', 'kitchen'],
    icon: KnifeBreadIcon,
  },
  {
    key: 'spoon',
    label: 'Spoon',
    group: 'Food',
    aliases: ['spoon', 'utensils', 'soup'],
    icon: SpoonIcon,
  },
  {
    key: 'salad',
    label: 'Salad',
    group: 'Food',
    aliases: ['salad', 'greens', 'healthy', 'lunch'],
    icon: SaladIcon,
  },
  {
    key: 'cooking_pot',
    label: 'Cooking',
    group: 'Food',
    aliases: ['pot', 'cooking', 'culinary', 'kitchen'],
    icon: Pot01Icon,
  },
  {
    key: 'kettle',
    label: 'Kettle',
    group: 'Food',
    aliases: ['kettle', 'hot water', 'tea'],
    icon: KettleIcon,
  },
  {
    key: 'fridge',
    label: 'Fridge',
    group: 'Food',
    aliases: ['fridge', 'refrigerator', 'kitchen'],
    icon: FridgeIcon,
  },
  {
    key: 'microwave',
    label: 'Microwave',
    group: 'Food',
    aliases: ['microwave', 'heat', 'kitchen'],
    icon: MicrowaveIcon,
  },
  {
    key: 'oven',
    label: 'Oven',
    group: 'Food',
    aliases: ['oven', 'bake', 'kitchen'],
    icon: OvenIcon,
  },
  {
    key: 'blender',
    label: 'Blender',
    group: 'Food',
    aliases: ['blender', 'smoothie', 'mix'],
    icon: BlenderIcon,
  },
  {
    key: 'whisk',
    label: 'Whisk',
    group: 'Food',
    aliases: ['whisk', 'baking', 'cooking'],
    icon: WhiskIcon,
  },
  {
    key: 'spatula',
    label: 'Spatula',
    group: 'Food',
    aliases: ['spatula', 'cooking', 'kitchen'],
    icon: SpatulaIcon,
  },
  {
    key: 'napkins',
    label: 'Napkins',
    group: 'Food',
    aliases: ['napkins', 'lunch', 'cafeteria'],
    icon: Napkins01Icon,
  },
  {
    key: 'egg',
    label: 'Egg',
    group: 'Food',
    aliases: ['egg', 'breakfast', 'cooking'],
    icon: EggIcon,
  },
  // Sports and outdoors
  {
    key: 'sports',
    label: 'Sports',
    group: 'Sports',
    aliases: ['sports', 'gym', 'fitness', 'athletics', 'workout'],
    icon: Dumbbell01Icon,
  },
  {
    key: 'fitness',
    label: 'Fitness',
    group: 'Sports',
    aliases: ['fitness', 'gym', 'exercise', 'wellness'],
    icon: YogaBallIcon,
  },
  {
    key: 'running',
    label: 'Running',
    group: 'Sports',
    aliases: ['running', 'track', 'cross country', 'shoes'],
    icon: RunningShoesIcon,
  },
  {
    key: 'swimming',
    label: 'Swimming',
    group: 'Sports',
    aliases: ['swimming', 'pool', 'swim'],
    icon: SwimmingIcon,
  },
  {
    key: 'bowling',
    label: 'Bowling',
    group: 'Sports',
    aliases: ['bowling', 'sport', 'fun', 'outing'],
    icon: BowlingIcon,
  },
  {
    key: 'football',
    label: 'Football',
    group: 'Sports',
    aliases: ['football', 'sport', 'ball'],
    icon: FootballIcon,
  },
  {
    key: 'biking',
    label: 'Biking',
    group: 'Sports',
    aliases: ['bike', 'biking', 'cycling'],
    icon: BikeIcon,
  },
  {
    key: 'camper',
    label: 'Camping',
    group: 'Sports',
    aliases: ['camper', 'camping', 'outdoors'],
    icon: CamperIcon,
  },
  {
    key: 'campfire',
    label: 'Campfire',
    group: 'Sports',
    aliases: ['campfire', 'camp', 'outdoors'],
    icon: CampfireIcon,
  },
  {
    key: 'tent',
    label: 'Tent',
    group: 'Sports',
    aliases: ['tent', 'camping', 'outdoors'],
    icon: TentIcon,
  },
  {
    key: 'mountain',
    label: 'Mountain',
    group: 'Sports',
    aliases: ['mountain', 'hiking', 'outdoors', 'desert', 'dunes'],
    icon: MountainIcon,
  },
  {
    key: 'beach',
    label: 'Beach',
    group: 'Sports',
    aliases: ['beach', 'ocean', 'shell', 'shells', 'field trip'],
    icon: Beach02Icon,
  },
  {
    key: 'island',
    label: 'Island',
    group: 'Sports',
    aliases: ['island', 'geography', 'beach'],
    icon: IslandIcon,
  },
  {
    key: 'ferry',
    label: 'Ferry',
    group: 'Sports',
    aliases: ['ferry', 'boat', 'ship', 'transit', 'water'],
    icon: FerryBoatIcon,
  },
  {
    key: 'anchor',
    label: 'Anchor',
    group: 'Sports',
    aliases: ['anchor', 'boat', 'navy'],
    icon: AnchorIcon,
  },
  {
    key: 'sailboat',
    label: 'Sailboat',
    group: 'Sports',
    aliases: ['sailboat', 'sailing', 'water'],
    icon: SailboatIcon,
  },
  {
    key: 'plane',
    label: 'Plane',
    group: 'Sports',
    aliases: ['plane', 'flight', 'travel', 'airport'],
    icon: PlaneIcon,
  },
  {
    key: 'train',
    label: 'Train',
    group: 'Sports',
    aliases: ['train', 'rail', 'transit'],
    icon: Train01Icon,
  },
  {
    key: 'journey',
    label: 'Route',
    group: 'Sports',
    aliases: ['route', 'path', 'directions', 'journey'],
    icon: Route01Icon,
  },
  {
    key: 'travel',
    label: 'Travel',
    group: 'Sports',
    aliases: ['travel', 'trip', 'luggage', 'journey'],
    icon: TravelBagIcon,
  },
  // Nature and science
  {
    key: 'sun',
    label: 'Sun',
    group: 'Nature',
    aliases: ['sun', 'sunny', 'weather'],
    icon: Sun01Icon,
  },
  {
    key: 'moon',
    label: 'Moon',
    group: 'Nature',
    aliases: ['moon', 'night', 'evening'],
    icon: MoonIcon,
  },
  {
    key: 'sunset',
    label: 'Sunset',
    group: 'Nature',
    aliases: ['sunset', 'evening', 'sky'],
    icon: SunsetIcon,
  },
  {
    key: 'sunrise',
    label: 'Sunrise',
    group: 'Nature',
    aliases: ['sunrise', 'morning'],
    icon: SunriseIcon,
  },
  {
    key: 'rainbow',
    label: 'Rainbow',
    group: 'Nature',
    aliases: ['rainbow', 'weather', 'sky'],
    icon: RainbowIcon,
  },
  {
    key: 'rain',
    label: 'Rain',
    group: 'Nature',
    aliases: ['rain', 'weather', 'storm'],
    icon: RainIcon,
  },
  {
    key: 'snow',
    label: 'Snow',
    group: 'Nature',
    aliases: ['snow', 'winter', 'snow day'],
    icon: SnowIcon,
  },
  {
    key: 'eclipse',
    label: 'Eclipse',
    group: 'Nature',
    aliases: ['eclipse', 'space', 'science'],
    icon: EclipseIcon,
  },
  {
    key: 'plant',
    label: 'Plant',
    group: 'Nature',
    aliases: ['plant', 'botany', 'garden', 'green'],
    icon: Plant01Icon,
  },
  {
    key: 'plant2',
    label: 'Seedling',
    group: 'Nature',
    aliases: ['sprout', 'seedling', 'garden', 'growth'],
    icon: SproutIcon,
  },
  {
    key: 'snail',
    label: 'Snail',
    group: 'Nature',
    aliases: ['snail', 'nature', 'slow'],
    icon: SnailIcon,
  },
  {
    key: 'feather',
    label: 'Feather',
    group: 'Nature',
    aliases: ['feather', 'bird', 'writing'],
    icon: FeatherIcon,
  },
  {
    key: 'bird',
    label: 'Bird',
    group: 'Nature',
    aliases: ['bird', 'nature', 'mascot'],
    icon: BirdIcon,
  },
  {
    key: 'fish',
    label: 'Fish',
    group: 'Nature',
    aliases: ['fish', 'aquarium', 'marine biology'],
    icon: FishIcon,
  },
  {
    key: 'cat',
    label: 'Cat',
    group: 'Nature',
    aliases: ['cat', 'pet', 'mascot'],
    icon: CatIcon,
  },
  {
    key: 'paw',
    label: 'Paw',
    group: 'Nature',
    aliases: ['paw', 'pet', 'animal', 'mascot'],
    icon: PawPrintIcon,
  },
  {
    key: 'gem',
    label: 'Gem',
    group: 'Nature',
    aliases: ['gem', 'geology', 'treasure', 'rock'],
    icon: GemIcon,
  },
  {
    key: 'diamond',
    label: 'Diamond',
    group: 'Nature',
    aliases: ['diamond', 'gem', 'geology'],
    icon: DiamondIcon,
  },
  // Celebrations
  {
    key: 'party',
    label: 'Party',
    group: 'Celebrations',
    aliases: ['party', 'celebration', 'dance'],
    icon: PartyIcon,
  },
  {
    key: 'gift',
    label: 'Gift',
    group: 'Celebrations',
    aliases: ['gift', 'present', 'reward'],
    icon: GiftIcon,
  },
  {
    key: 'fireworks',
    label: 'Fireworks',
    group: 'Celebrations',
    aliases: ['fireworks', 'celebration'],
    icon: FireworksIcon,
  },
  {
    key: 'sparkles',
    label: 'Sparkles',
    group: 'Celebrations',
    aliases: ['sparkles', 'special', 'new'],
    icon: SparklesIcon,
  },
  {
    key: 'lantern',
    label: 'Lantern',
    group: 'Celebrations',
    aliases: ['lantern', 'light', 'festival'],
    icon: LanternIcon,
  },
  {
    key: 'ticket',
    label: 'Ticket',
    group: 'Celebrations',
    aliases: ['ticket', 'event', 'admission'],
    icon: Ticket01Icon,
  },
  {
    key: 'flag',
    label: 'Flag',
    group: 'Celebrations',
    aliases: ['flag', 'marker', 'signal'],
    icon: Flag02Icon,
  },
  {
    key: 'balloons',
    label: 'Balloons',
    group: 'Celebrations',
    aliases: ['balloon', 'balloons', 'party', 'celebration'],
    icon: BalloonsIcon,
  },
  // Clothing
  {
    key: 'hoodie',
    label: 'Hoodie',
    group: 'Clothing',
    aliases: ['hoodie', 'sweatshirt', 'spirit wear'],
    icon: HoodieIcon,
  },
  {
    key: 'dress',
    label: 'Dress',
    group: 'Clothing',
    aliases: ['dress', 'formal', 'clothing'],
    icon: Dress01Icon,
  },
  {
    key: 'apron',
    label: 'Apron',
    group: 'Clothing',
    aliases: ['apron', 'cooking', 'art', 'lab'],
    icon: ApronIcon,
  },
  {
    key: 'shirt',
    label: 'Shirt',
    group: 'Clothing',
    aliases: ['shirt', 'spirit wear', 'clothing'],
    icon: Shirt01Icon,
  },
  {
    key: 'shoes',
    label: 'Shoes',
    group: 'Clothing',
    aliases: ['shoes', 'sneakers', 'footwear', 'pe'],
    icon: ShoesIcon,
  },
  {
    key: 'hat',
    label: 'Hat',
    group: 'Clothing',
    aliases: ['hat', 'cap', 'clothing'],
    icon: HatIcon,
  },
  {
    key: 'socks',
    label: 'Socks',
    group: 'Clothing',
    aliases: ['socks', 'clothing'],
    icon: SocksIcon,
  },
  {
    key: 'glasses',
    label: 'Glasses',
    group: 'Clothing',
    aliases: ['glasses', 'vision', 'sight'],
    icon: GlassesIcon,
  },
  // Office and supplies
  {
    key: 'briefcase',
    label: 'Briefcase',
    group: 'Office',
    aliases: ['briefcase', 'work', 'career', 'business'],
    icon: Briefcase01Icon,
  },
  {
    key: 'folder',
    label: 'Folder',
    group: 'Office',
    aliases: ['folder', 'files', 'documents'],
    icon: Folder01Icon,
  },
  {
    key: 'archive',
    label: 'Archive',
    group: 'Office',
    aliases: ['archive', 'records', 'storage'],
    icon: Archive01Icon,
  },
  {
    key: 'news',
    label: 'News',
    group: 'Office',
    aliases: ['news', 'newspaper', 'journalism', 'announcements'],
    icon: News01Icon,
  },
  {
    key: 'tag',
    label: 'Tag',
    group: 'Office',
    aliases: ['tag', 'label'],
    icon: Tag02Icon,
  },
  {
    key: 'label',
    label: 'Label',
    group: 'Office',
    aliases: ['label', 'name', 'tag', 'sticker'],
    icon: LabelIcon,
  },
  {
    key: 'discount',
    label: 'Discount',
    group: 'Office',
    aliases: ['discount', 'sale', 'spirit wear'],
    icon: DiscountIcon,
  },
  {
    key: 'percent',
    label: 'Percent',
    group: 'Office',
    aliases: ['percent', 'math', 'discount'],
    icon: PercentIcon,
  },
  {
    key: 'contract',
    label: 'Contract',
    group: 'Office',
    aliases: ['contract', 'agreement', 'signature'],
    icon: ContractsIcon,
  },
  {
    key: 'key',
    label: 'Key',
    group: 'Office',
    aliases: ['key', 'access', 'lock'],
    icon: Key02Icon,
  },
  {
    key: 'lock',
    label: 'Lock',
    group: 'Office',
    aliases: ['lock', 'secure'],
    icon: LockIcon,
  },
  {
    key: 'safe',
    label: 'Safe',
    group: 'Office',
    aliases: ['safe', 'vault', 'secure'],
    icon: SafeIcon,
  },
  {
    key: 'money',
    label: 'Money',
    group: 'Office',
    aliases: ['money', 'cash', 'payment'],
    icon: Money02Icon,
  },
  {
    key: 'bank',
    label: 'Bank',
    group: 'Office',
    aliases: ['bank', 'finance'],
    icon: BankIcon,
  },
  {
    key: 'cash',
    label: 'Cash',
    group: 'Office',
    aliases: ['cash', 'money', 'payment'],
    icon: Cash01Icon,
  },
  {
    key: 'savings',
    label: 'Savings',
    group: 'Office',
    aliases: ['savings', 'piggy bank', 'money'],
    icon: PiggyBankIcon,
  },
  {
    key: 'tax',
    label: 'Tax',
    group: 'Office',
    aliases: ['tax', 'finance'],
    icon: TaxiIcon,
  },
  {
    key: 'receipt',
    label: 'Receipt',
    group: 'Office',
    aliases: ['receipt', 'payment', 'proof'],
    icon: ReceiptIcon,
  },
  {
    key: 'chart',
    label: 'Chart',
    group: 'Office',
    aliases: ['chart', 'graph', 'data'],
    icon: ChartIcon,
  },
  {
    key: 'table',
    label: 'Table',
    group: 'Office',
    aliases: ['table', 'data', 'grid'],
    icon: Table02Icon,
  },
  {
    key: 'layout',
    label: 'Layout',
    group: 'Office',
    aliases: ['layout', 'design', 'arrangement'],
    icon: Layout01Icon,
  },
  {
    key: 'calendar',
    label: 'Calendar',
    group: 'Office',
    aliases: ['calendar', 'date', 'schedule', 'appointment'],
    icon: Calendar02Icon,
  },
  {
    key: 'clock',
    label: 'Clock',
    group: 'Office',
    aliases: ['clock', 'time', 'schedule'],
    icon: Clock02Icon,
  },
  {
    key: 'alarm',
    label: 'Alarm',
    group: 'Office',
    aliases: ['alarm', 'clock', 'time'],
    icon: AlarmClockIcon,
  },
  {
    key: 'bell',
    label: 'Bell',
    group: 'Office',
    aliases: ['bell', 'notification', 'alert'],
    icon: BellIcon,
  },
  {
    key: 'timer',
    label: 'Timer',
    group: 'Office',
    aliases: ['timer', 'countdown', 'time'],
    icon: Timer02Icon,
  },
  {
    key: 'refresh',
    label: 'Refresh',
    group: 'Office',
    aliases: ['refresh', 'sync', 'update'],
    icon: RefreshIcon,
  },
  {
    key: 'copy',
    label: 'Copy',
    group: 'Office',
    aliases: ['copy', 'duplicate'],
    icon: Copy02Icon,
  },
  {
    key: 'scissors',
    label: 'Scissors',
    group: 'Office',
    aliases: ['scissors', 'cut'],
    icon: ScissorsIcon,
  },
  {
    key: 'mail',
    label: 'Mail',
    group: 'Office',
    aliases: ['mail', 'email', 'post'],
    icon: Mail02Icon,
  },
  {
    key: 'mailbox',
    label: 'Mailbox',
    group: 'Office',
    aliases: ['mailbox', 'mail', 'letters'],
    icon: Mailbox01Icon,
  },
  {
    key: 'package',
    label: 'Package',
    group: 'Office',
    aliases: ['package', 'delivery'],
    icon: Package01Icon,
  },
  {
    key: 'shopping',
    label: 'Shopping bag',
    group: 'Office',
    aliases: ['bag', 'shopping', 'spirit wear'],
    icon: ShoppingBag01Icon,
  },
  {
    key: 'card_payment',
    label: 'Card payment',
    group: 'Office',
    aliases: ['credit', 'card', 'payment'],
    icon: CreditCardIcon,
  },
  {
    key: 'box',
    label: 'Box',
    group: 'Office',
    aliases: ['box', 'storage', 'package'],
    icon: BoxIcon,
  },
  {
    key: 'bucket',
    label: 'Bucket',
    group: 'Office',
    aliases: ['bucket', 'cleaning', 'water'],
    icon: BucketIcon,
  },
  {
    key: 'jar',
    label: 'Jar',
    group: 'Office',
    aliases: ['jar', 'container', 'storage'],
    icon: JarIcon,
  },
  {
    key: 'cabinet',
    label: 'Cabinet',
    group: 'Office',
    aliases: ['cabinet', 'storage', 'files'],
    icon: Cabinet01Icon,
  },
  {
    key: 'chair',
    label: 'Chair',
    group: 'Office',
    aliases: ['chair', 'seat', 'classroom'],
    icon: Chair01Icon,
  },
  // Technology
  {
    key: 'technology',
    label: 'Technology',
    group: 'Technology',
    aliases: ['technology', 'laptop', 'computer', 'tech', 'chromebook'],
    icon: LaptopIcon,
  },
  {
    key: 'keyboard',
    label: 'Keyboard',
    group: 'Technology',
    aliases: ['keyboard', 'typing', 'computer'],
    icon: KeyboardIcon,
  },
  {
    key: 'mouse',
    label: 'Mouse',
    group: 'Technology',
    aliases: ['mouse', 'computer', 'click'],
    icon: Mouse01Icon,
  },
  {
    key: 'smartphone',
    label: 'Phone',
    group: 'Technology',
    aliases: ['phone', 'smartphone', 'call', 'mobile'],
    icon: SmartPhone01Icon,
  },
  {
    key: 'wifi',
    label: 'Wi-Fi',
    group: 'Technology',
    aliases: ['wifi', 'internet', 'network'],
    icon: Wifi01Icon,
  },
  {
    key: 'robot',
    label: 'Robotics',
    group: 'Technology',
    aliases: ['robot', 'robotics', 'stem', 'engineering'],
    icon: Robot01Icon,
  },
  // Tools and utilities
  {
    key: 'plug',
    label: 'Plug',
    group: 'Tools',
    aliases: ['plug', 'power', 'electricity'],
    icon: Plug01Icon,
  },
  {
    key: 'solar',
    label: 'Solar',
    group: 'Tools',
    aliases: ['solar', 'energy', 'environment'],
    icon: SolarEnergyIcon,
  },
  {
    key: 'battery',
    label: 'Battery',
    group: 'Tools',
    aliases: ['battery', 'power'],
    icon: BatteryIcon,
  },
  {
    key: 'fuel',
    label: 'Fuel',
    group: 'Tools',
    aliases: ['fuel', 'energy', 'gas'],
    icon: FuelIcon,
  },
  {
    key: 'gauge',
    label: 'Gauge',
    group: 'Tools',
    aliases: ['gauge', 'meter', 'measure'],
    icon: GaugeIcon,
  },
  {
    key: 'hammer',
    label: 'Hammer',
    group: 'Tools',
    aliases: ['hammer', 'tools', 'shop', 'construction'],
    icon: HammerIcon,
  },
  {
    key: 'drill',
    label: 'Drill',
    group: 'Tools',
    aliases: ['drill', 'tools', 'shop'],
    icon: DrillIcon,
  },
  {
    key: 'tape_measure',
    label: 'Tape measure',
    group: 'Tools',
    aliases: ['tape', 'measure', 'construction'],
    icon: TapeMeasureIcon,
  },
  {
    key: 'thread',
    label: 'Thread',
    group: 'Tools',
    aliases: ['thread', 'sewing', 'fashion'],
    icon: ThreadIcon,
  },
  {
    key: 'cable',
    label: 'Cable',
    group: 'Tools',
    aliases: ['cable', 'wire', 'tech'],
    icon: ThreadIcon,
  },
  {
    key: 'brick',
    label: 'Brick',
    group: 'Tools',
    aliases: ['brick', 'wall', 'construction'],
    icon: BrickWallIcon,
  },
  {
    key: 'logout',
    label: 'Log out',
    group: 'Tools',
    aliases: ['log out', 'sign out', 'exit', 'leave'],
    icon: Logout02Icon,
  },
  {
    key: 'generic',
    label: 'More (grid)',
    group: 'Symbols',
    aliases: ['more', 'grid', 'other', 'general'],
    icon: GridIcon,
  },
  {
    key: 'chat',
    label: 'Conversation',
    group: 'Symbols',
    aliases: ['chat', 'conversation', 'talk', 'message', 'counselor'],
    icon: BubbleChatIcon,
  },
];

export const CATEGORY_ICONS: Record<string, CategoryIcon> = Object.fromEntries(
  CATEGORY_ICON_REGISTRY.map((entry) => [entry.key, entry.icon]),
);

export type CategoryIconKey = (typeof CATEGORY_ICON_REGISTRY)[number]['key'];

export function iconForCategoryKey(iconKey: string): CategoryIcon {
  return CATEGORY_ICONS[iconKey] ?? GridIcon;
}

/** Normalizes icon search text: case, whitespace, and punctuation. */
export function normalizeIconQuery(value: string): string {
  return value
    .toLowerCase()
    .replace(/[_-]+/g, ' ')
    .replace(/[^a-z0-9 ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Local instant icon search over labels, keys, and aliases. */
export function searchCategoryIcons(query: string): readonly CategoryIconDefinition[] {
  const normalized = normalizeIconQuery(query);
  if (normalized === '') return CATEGORY_ICON_REGISTRY;
  const tokens = normalized.split(' ').filter(Boolean);
  return CATEGORY_ICON_REGISTRY.filter((entry) => {
    const haystack = normalizeIconQuery([entry.label, entry.key, ...entry.aliases].join(' '));
    return tokens.every((token) => haystack.includes(token));
  });
}

/** Picker groups in registry order for ComboboxGroup rendering. */
export function categoryIconGroups(
  entries: readonly CategoryIconDefinition[] = CATEGORY_ICON_REGISTRY,
): { group: string; icons: CategoryIconDefinition[] }[] {
  const groups = new Map<string, CategoryIconDefinition[]>();
  for (const entry of entries) {
    const list = groups.get(entry.group);
    if (list) list.push(entry);
    else groups.set(entry.group, [entry]);
  }
  return [...groups.entries()].map(([group, icons]) => ({ group, icons }));
}

export const CATEGORY_TONES = [
  'aqua',
  'rose',
  'violet',
  'amber',
  'blue',
  'green',
  'slate',
  'neutral',
] as const;

export type CategoryToneKey = (typeof CATEGORY_TONES)[number];

export function isCategoryToneKey(value: string): value is CategoryToneKey {
  return (CATEGORY_TONES as readonly string[]).includes(value);
}

// Centralized tile tones. Low saturation, generous radius, clear interactive
// states. Icon + text stay authoritative; color is supplemental only and the
// border keeps tiles distinct under forced-colors.
export const tileTone = cva(
  'h-auto min-h-28 flex-col gap-2 rounded-3xl border-2 p-4 text-base font-semibold wrap-break-word whitespace-normal forced-colors:border-[ButtonText]',
  {
    variants: {
      tone: {
        aqua: 'border-cyan-700/20 bg-cyan-100 text-cyan-950 hover:bg-cyan-200/70 dark:border-cyan-300/20 dark:bg-cyan-950 dark:text-cyan-50 dark:hover:bg-cyan-900',
        rose: 'border-rose-700/20 bg-rose-100 text-rose-950 hover:bg-rose-200/70 dark:border-rose-300/20 dark:bg-rose-950 dark:text-rose-50 dark:hover:bg-rose-900',
        violet:
          'border-violet-700/20 bg-violet-100 text-violet-950 hover:bg-violet-200/70 dark:border-violet-300/20 dark:bg-violet-950 dark:text-violet-50 dark:hover:bg-violet-900',
        amber:
          'border-amber-700/20 bg-amber-100 text-amber-950 hover:bg-amber-200/70 dark:border-amber-300/20 dark:bg-amber-950 dark:text-amber-50 dark:hover:bg-amber-900',
        blue: 'border-blue-700/20 bg-blue-100 text-blue-950 hover:bg-blue-200/70 dark:border-blue-300/20 dark:bg-blue-950 dark:text-blue-50 dark:hover:bg-blue-900',
        green:
          'border-green-700/20 bg-green-100 text-green-950 hover:bg-green-200/70 dark:border-green-300/20 dark:bg-green-950 dark:text-green-50 dark:hover:bg-green-900',
        slate:
          'border-slate-700/20 bg-slate-200 text-slate-900 hover:bg-slate-300/70 dark:border-slate-300/20 dark:bg-slate-800 dark:text-slate-50 dark:hover:bg-slate-700',
        neutral: 'border-border bg-muted text-foreground hover:bg-muted/60 dark:hover:bg-muted/40',
      },
    },
  },
);

export function toneForCategoryKey(toneKey: string): CategoryToneKey {
  return isCategoryToneKey(toneKey) ? toneKey : 'neutral';
}

/** Human-facing student-surface labels. The DB persists `secondary`; the UI says "More". */
export function surfaceLabel(surface: string): string {
  switch (surface) {
    case 'primary':
      return 'Primary';
    case 'hidden':
      return 'Hidden';
    default:
      return 'More';
  }
}

export type CategoryPickerMode = 'auto' | 'list' | 'search';

/** Destination count at or above which `auto` resolves to search. */
export const CATEGORY_AUTO_SEARCH_THRESHOLD = 8;

export function resolveCategoryPicker(
  pickerMode: string,
  destinationCount: number,
): 'list' | 'search' {
  if (pickerMode === 'list') return 'list';
  if (pickerMode === 'search') return 'search';
  return destinationCount >= CATEGORY_AUTO_SEARCH_THRESHOLD ? 'search' : 'list';
}

export const CATEGORY_PICKER_MODE_OPTIONS: {
  value: CategoryPickerMode;
  label: string;
  description: string;
}[] = [
  {
    value: 'auto',
    label: 'Automatic',
    description: 'Use a simple list for a few choices and search for larger sets.',
  },
  {
    value: 'list',
    label: 'List',
    description: 'Always show choices as a simple list.',
  },
  {
    value: 'search',
    label: 'Search',
    description: 'Always let students search teacher or room.',
  },
];

export const CATEGORY_ICON_OPTIONS: { value: string; label: string }[] = CATEGORY_ICON_REGISTRY.map(
  (entry) => ({ value: entry.key, label: entry.label }),
);

export const CATEGORY_TONE_OPTIONS: { value: CategoryToneKey; label: string }[] = [
  { value: 'aqua', label: 'Aqua' },
  { value: 'rose', label: 'Rose' },
  { value: 'violet', label: 'Violet' },
  { value: 'amber', label: 'Amber' },
  { value: 'blue', label: 'Blue' },
  { value: 'green', label: 'Green' },
  { value: 'slate', label: 'Slate' },
  { value: 'neutral', label: 'Neutral' },
];

/** Normalizes destination search text: case, whitespace, punctuation. */
export function normalizeDestinationQuery(value: string): string {
  return normalizeIconQuery(value);
}

export interface DestinationSearchEntry {
  readonly displayName: string;
  readonly locationName: string;
  readonly locationCode: string | null;
  readonly floorLabel: string | null;
  readonly staffDisplayNames: readonly string[];
  readonly sectionLabels: readonly string[];
}

/**
 * Generic destination search matching: every normalized query token must
 * appear somewhere in the normalized destination text (name, room, code,
 * floor, staff display names, section labels). Case, whitespace, and
 * punctuation insensitive. Never branches on category names.
 */
export function matchDestinationSearch(entry: DestinationSearchEntry, rawQuery: string): boolean {
  const tokens = normalizeDestinationQuery(rawQuery).split(' ').filter(Boolean);
  if (tokens.length === 0) return true;
  const haystack = normalizeDestinationQuery(
    [
      entry.displayName,
      entry.locationName,
      entry.locationCode ?? '',
      entry.floorLabel ?? '',
      ...entry.staffDisplayNames,
      ...entry.sectionLabels,
    ].join(' '),
  );
  return tokens.every((token) => haystack.includes(token));
}
